AWSTemplateFormatVersion: "2010-09-09"
Parameters: 
  MyglobalIP:
    Description: SecurityGroup for SSH into EC2
    Type: String
  Keypair:
    Type: String
    Default: ''
Resources:
###
#Launch template
### 
  WebSVLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: websv-launch-template
      LaunchTemplateData:
        UserData:
          Fn::Base64: |
            #!/bin/bash
            ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
            cp -p /etc/sysconfig/clock /etc/sysconfig/clock.org ; sudo sed -i 's/\"UTC\"/\"Asia\/Tokyo\"/g' /etc/sysconfig/clock
            localectl set-locale LANG=ja_JP.utf8
            localectl set-keymap jp106
            yum update -y
            reboot
###
#Web Instance
### 
  WebSVInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0e3861265a3a335cc
      KeyName: !Ref Keypair
      InstanceType: t2.micro
      AvailabilityZone: ap-northeast-1c
      Tenancy: default
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !ImportValue PublicSubnetc
          GroupSet: 
            - !ImportValue WebSVSG
      IamInstanceProfile: !ImportValue s3Role
      Tags:
          - Key: Name
            Value: kadai-WebSV
      LaunchTemplate:
        LaunchTemplateId: !Ref WebSVLaunchTemplate
        Version: !GetAtt WebSVLaunchTemplate.LatestVersionNumber
###
#EIP
### 
  EipWebSV:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref WebSVInstance
###
#SecurityGroup for SSH into EC2
### 
  WebSecurityGroupIngress2:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !ImportValue WebSVSG
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      CidrIp: !Ref MyglobalIP
Outputs:
  WebSVInstanceOutput:
    Value:  
      Ref: WebSVInstance
    Export:
      Name: WebSV